apiVersion: v1
kind: ConfigMap
metadata:
  name: json-configmap
  namespace: default
data:
  config.json: |-
    {
      "current_env" : "gcp-development-minikube",
      "Directory_Type" : "folder",
      "Input_Environment_Type" : "gcs",
      "Input_Environment_Location" : "raw-data",
      "Output_Environment_Type" : "bigquery",
      "Output_Environment_Location" : "test_ds",
      "report_location": "reports",
      "LARGE_SYSTEMS_DJANGO_CONFIGMAP_value1": "very",
      "LARGE_SYSTEMS_DJANGO_CONFIGMAP_value2": "cool"
    }