apiVersion: apps/v1
kind: Deployment
metadata:
  name: large-systems-django-deployment
  labels:
    app: large-systems-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: large-systems-django
      env: production
  template:
    metadata:
      labels:
        app: large-systems-django
        env: production
    spec:
      containers:
      - name: large-systems-django
        image: ha33ona/python:latest
        volumeMounts:
          - mountPath: /etc/config
            name: json-configmap-volume
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "512Mi"
            cpu: "1"

      volumes:
        - name: json-configmap-volume
          configMap:
            name: json-configmap
