apiVersion: v1
kind: Pod
metadata:
  name: large-systems-django-production
  labels:
    app: large-systems-django-production
spec:
  containers:
  - name: large-systems-django-production
    image: ha33ona/python:main
    ports:
    - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: large-systems-django-production-service
spec:
  type: NodePort
  selector:
    app: large-systems-django-production
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000