apiVersion: v1
kind: Service
metadata:
  name: large-systems-django-service
spec:
  type: LoadBalancer
  selector:
    app: large-systems-django
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000