apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: large-systems-django-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: large-systems-django-statefulset
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
