apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: large-systems-django-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  resourceNames: ["large-systems-django-statefulset"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  resourceNames: ["large-systems-django-service"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
